package com.example.domain.usecase

import com.example.domain.models.GameMode
import com.example.domain.models.RatingElementModel
import com.example.domain.models.ResultModel
import com.example.domain.repository.ApiRepository

class GetRatingListUseCase(
    private val apiRepository: ApiRepository
) {

    suspend fun execute(gameMode: GameMode, examplesCategory: Int, mathOperations: List<String>, difficulty: Int, limit: Int, offset: Int): ResultModel<List<RatingElementModel>> {
        return apiRepository.getRatingList(
            gameMode = gameMode,
            examplesCategory = examplesCategory,
            mathOperations = mathOperations,
            difficulty = difficulty,
            limit = limit,
            offset = offset
        )
//        val list = listOf(
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "al",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "sergey",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            ),
//            RatingElementModel(
//                gameMode = GameMode.CountMode,
//                duration = 30,
//                mathOperations = listOf("+"),
//                examplesCategory = 10,
//                username = "iksanov",
//                totalCount = 10,
//                correctCount = 7,
//                userId = 0,
//                gameSessionId = 0,
//                createdAt = "0"
//            )
//        )
//
//        return ResultModel.success(
//            data = list.subList(offset, offset + limit)
//        )
    }

}